service: fitness-platform-api

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  stage: ${opt:stage}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:PutItem
            - dynamodb:GetItem
            - dynamodb:Scan
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource: arn:aws:dynamodb:${self:provider.region}:*:table/FitnessSessions-${self:provider.stage}

functions:
  createWorkout:
    handler: createWorkout.handler
    environment:
      FITNESS_SESSIONS_TABLE: FitnessSessions-${self:provider.stage}
    events:
      - http:
          path: workouts
          method: post

  getWorkouts:
    handler: getWorkouts.handler
    environment:
      FITNESS_SESSIONS_TABLE: FitnessSessions-${self:provider.stage}
    events:
      - http:
          path: workouts
          method: get

  updateWorkout:
    handler: updateWorkout.handler
    environment:
      FITNESS_SESSIONS_TABLE: FitnessSessions-${self:provider.stage}
    events:
      - http:
          path: workouts
          method: put

  deleteWorkout:
    handler: deleteWorkout.handler
    environment:
      FITNESS_SESSIONS_TABLE: FitnessSessions-${self:provider.stage}
    events:
      - http:
          path: workouts
          method: delete

resources:
  Resources:
    FitnessTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: FitnessSessions-${self:provider.stage}
        AttributeDefinitions:
          - AttributeName: SessionId
            AttributeType: S
          - AttributeName: UserName
            AttributeType: S
        KeySchema:
          - AttributeName: SessionId
            KeyType: HASH
          - AttributeName: UserName
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
